name: DOTNET CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Code and Run the Unit Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: LongestIncreasingSubsequence

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore   

    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      
    - name: Install ReportGenerator tool
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Create Code Coverage Report
      run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverage" -reporttypes:Html
      
    - name: List coverage directory
      run: ls -al coverage

    - name: Upload coverage report to artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: LongestIncreasingSubsequence/coverage/
